import NavBar from "@/components/NavBar";
import "./../styles/global.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="overflow-x-hidden bg-background">
        <main>{children}</main>
        <NavBar />
      </body>
    </html>
  );
}
